
import java.awt.Color;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHADOW
 */
public class Edt_fram extends javax.swing.JFrame {
    private jour j=new jour();
    private heur h=new heur();
    private promo p=new promo();
    private session ss=new session();
    private emploi eml=new emploi();
    private contien c=new contien();
    private ArrayList<jour> jl=j.getjourlist("");
    private ArrayList<heur> hl=h.getheurlist("");
    private ArrayList<promo> pl=p.getpromolist("");
    private ArrayList<session> sl=new ArrayList<>();
    private ArrayList<emploi> ne=new ArrayList<>();
    private ArrayList<ArrayList<emploi>> nel=new ArrayList<>();
    private enseign es=new enseign();
    private int code_s,sem=0,index=0;
    
    /**
     * Creates new form seance
     */
    public Edt_fram() {
        initComponents();
        jMenuBar1.add(Box.createGlue());
        jMenuBar1.add(jMenu4);
        jMenuBar1.add(jMenu8);
        jMenuBar1.add(jMenu2);
        jMenu9.setSelected(true);
        load_session();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tpan1 = new javax.swing.JScrollPane();
        tpan2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        date_pan1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpan = new javax.swing.JTabbedPane();
        suiv = new javax.swing.JButton();
        prec = new javax.swing.JButton();
        ref = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jMenuItem1.setText("Suprimer");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jMenuItem2.setText("Consulter");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("Imprimer");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crée un nouveau emploi du temps");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, 430, 40));

        tpan2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout date_pan1Layout = new javax.swing.GroupLayout(date_pan1);
        date_pan1.setLayout(date_pan1Layout);
        date_pan1Layout.setHorizontalGroup(
            date_pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        date_pan1Layout.setVerticalGroup(
            date_pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(date_pan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(date_pan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        tpan2.addTab("tab2", jPanel2);

        tpan1.setViewportView(tpan2);

        jPanel8.add(tpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1000, 510));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setComponentPopupMenu(jPopupMenu1);
        table1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(table1);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, 510));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gérer emploi du temps");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 350, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1260, -1, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Crée un nouveau");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 1260, -1, 30));

        jLabel3.setText(" ");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 1280, 110, 40));

        tpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(tpan);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 1220, 540));

        suiv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        suiv.setText("Suivant");
        suiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suivActionPerformed(evt);
            }
        });
        jPanel8.add(suiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1260, 100, 30));

        prec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prec.setText("Précédent");
        prec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precActionPerformed(evt);
            }
        });
        jPanel8.add(prec, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 1260, 100, 30));

        ref.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ref.setForeground(new java.awt.Color(255, 255, 255));
        ref.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 1260, 50, 30));

        jScrollPane1.setViewportView(jPanel8);

        jMenu3.setText("Enseignant");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu5.setText("module");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu5MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("seance");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu6MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Promos");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu7MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu9.setText("EDT");
        jMenuBar1.add(jMenu9);

        jMenu1.setText("Utilisateur");
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Déconncter");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu8.setText("_");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu8MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Error-icon.png"))); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1350, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        try {
            code_s=sl.get(table1.getSelectedRow()).code;
            JOptionPane.showMessageDialog(null,ss.suprimer(code_s));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Selectioner une session");
        }
        load_session();
        tpan2.removeAll();
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed
        module_fram mf=new module_fram();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu5MousePressed

    private void jMenu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MousePressed
        seance sf=new seance();
        sf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu6MousePressed

    private void jMenu7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MousePressed
        promo_fram pf=new promo_fram();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu7MousePressed

    private void jMenu8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MousePressed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jMenu8MousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        System.exit(0);
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        Prof_fram pf=new Prof_fram();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu3MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Genere_EDT edt=new Genere_EDT();
        String[] options = {"Semestre 1", "Semestre 2"};
        String n = (String)JOptionPane.showInputDialog(null, "Quelle semaistre"," ", JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(n.equals("Semestre 1")) sem=1;
        if(n.equals("Semestre 2")) sem=2;
        //JOptionPane.showMessageDialog(null,"Charmement en cours veiller patinenter");
        Thread thread = new Thread("New Thread"){
                public void run(){
                    System.out.println("run by: " + getName());
                    if(sem!=0) nel = edt.getsolution2(sem);
                    index=0;
                    afficher();                    
                }
            };
            thread.start();
        //if(sem!=0) ne = edt.getsolution2(sem);
        //aficher_emploi2(tpan,ne,sem);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String response = JOptionPane.showInputDialog(null, "Entrer un nom pour EDT :", "");
        if ((response != null) && (response.length() > 0)) {
            int n=ss.add(response,sem);
            if (n!=0) {
                String s=eml.add(n,ne);
                JOptionPane.showMessageDialog(null,s);
            }
        }
        load_session();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        try {
            int i=table1.getSelectedRow();
            code_s=sl.get(i).code;
            Thread thread = new Thread("New Thread"){
                public void run(){
                    System.out.println("run by: " + getName());
                    aficher_emploi2(tpan2,eml.getemploilist(sl.get(i).code,0),sl.get(i).sem);
                }
            };
            thread.start();
            //aficher_emploi2(tpan2,eml.getemploilist(sl.get(i).code,0),sl.get(i).sem);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Selectioner une session");
        }
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
        ConBD.u=null;
        login l=new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu4MousePressed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        users_fram uf=new users_fram();
        uf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MousePressed

    private void precActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precActionPerformed
        if(nel.size() !=0){
            if(index>0){
                index--;
                afficher();
            }
        }
    }//GEN-LAST:event_precActionPerformed

    private void suivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suivActionPerformed
        if(nel.size() !=0){
            if(index<nel.size()-1){
                index++;
                afficher();
            }
        }
    }//GEN-LAST:event_suivActionPerformed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        imprimer im=new imprimer();
        im.afficher1(sl.get(table1.getSelectedRow()));        
    }//GEN-LAST:event_jMenuItem3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel date_pan1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton prec;
    private javax.swing.JLabel ref;
    private javax.swing.JButton suiv;
    private javax.swing.JTable table1;
    private javax.swing.JTabbedPane tpan;
    private javax.swing.JScrollPane tpan1;
    private javax.swing.JTabbedPane tpan2;
    // End of variables declaration//GEN-END:variables

    
    
    private void load_session(){
        sl = ss.getsessionlist("");
        DefaultTableModel model = (DefaultTableModel)table1.getModel();
        model.setRowCount(0);
        Object[] row = new Object[1];
        for(int i = 0; i < sl.size(); i++)
        {
            row[0] = sl.get(i).desc;
            model.addRow(row);
        }
    }
    private void afficher(){
        ne=nel.get(index);
        aficher_emploi2(tpan,ne,sem);
        ref.setText(1+index+"/"+nel.size());
    }
    private void aficher_emploi2(JTabbedPane t,ArrayList<emploi> e,int seme) {
        
        ArrayList<emploi> e1;        
        t.removeAll();
        int js=jl.size(),hs=hl.size();
        JPanel pan1,pan2,pan3 ;  
        JLabel lbl;
        String s;
        Color color = new Color(0, 0, 0);
        for(promo pr :pl){
            pan3=new JPanel(new GridLayout(2, 1, 5, 0));
            pan1=new JPanel(new GridLayout(hs+1, js+1, 2, 5));
            pan1.setBackground(Color.WHITE);
            e1=pr.element(e,sem);
            if(t==tpan2){
                MyButton mb=new MyButton("Modiffier", e1,code_s,pr.code,pr.nom);
                mb.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        //System.out.println(mb.e1);
                        salle_a ss=new salle_a(mb.e,mb.code_s,mb.code_p,mb.nom,seme);
                        ss.setVisible(true);
                    }
                });
                pan1.add(mb);
            }else pan1.add(new JLabel());
            for(int k=0;k<js;k++) {
                lbl=new JLabel(" "+jl.get(k).nom);
                lbl.setFont(new java.awt.Font("Tahoma", 1, 12));
                lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbl.setBorder(javax.swing.BorderFactory.createLineBorder(color));
                pan1.add(lbl);
            }
            for(int k=0;k<hs;k++){
                lbl=new JLabel(hl.get(k).nom);
                lbl.setFont(new java.awt.Font("Tahoma", 1, 12));
                lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbl.setBorder(javax.swing.BorderFactory.createLineBorder(color));
                pan1.add(lbl);                
                for(int l=0;l<js;l++){ 
                    s="<html>";
                    int r=0;
                    for(int n=0;n<e1.size();n++){
                        if(e1.get(n).j==jl.get(l).code && e1.get(n).h==hl.get(k).code) {
                            if(pr.nbr==1){
                                s=s+e1.get(n).lib+" "+e1.get(n).nom_t;
                                if(e1.get(n).salle!=0) s=s+e1.get(n).nom_sl;
                                if(t==tpan2) s=s+"<br> "+es.getenseignant(e1.get(n).m, e1.get(n).t, e1.get(n).grp);
                                s=s+"<br>";
                            }else {
                                if(e1.get(n).t==1) {
                                    s=s+e1.get(n).lib+" "+e1.get(n).nom_t;
                                    if(e1.get(n).salle!=0) s=s+" "+e1.get(n).nom_sl;
                                    if(t==tpan2) s=s+"<br>"+es.getenseignant(e1.get(n).m, e1.get(n).t, e1.get(n).grp);
                                    s=s+"<br>";
                                    r=1;
                                }
                                else {
                                    s=s+"&nbsp;G"+e1.get(n).grp+" "+e1.get(n).lib+" "+e1.get(n).nom_t;
                                    if(e1.get(n).salle!=0) s=s+" "+e1.get(n).nom_sl;
                                    if(t==tpan2) s=s+" "+es.getenseignant(e1.get(n).m, e1.get(n).t, e1.get(n).grp);
                                    s=s+"<br>";
                                }
                            }
                            
                            //System.out.println(e1.get(n).nom_m);
                        }                    
                    }
                    s=s+"</html><div style='padding:1px;text-align:left'>";
                    lbl=new JLabel(s);
                    if(pr.nbr==1 || r==1 ) lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    lbl.setBorder(javax.swing.BorderFactory.createLineBorder(color));
                    lbl.setFont(new java.awt.Font("Tahoma", 1, 12));
                    lbl.setSize(400, 300);
                    pan1.add(lbl);
                    r=0;
                }
            }
            ArrayList<contien> cl = c.getmcontienlist(pr.code, 0,seme);
            s="<html>";
            if(t==tpan2){
                responsable rs=new responsable();
                s=s+"<h2> &nbsp; &nbsp; Le président de l’équipe pédagogique est :"+rs.getresponsablelist(pr.code, seme).get(0).nom_e+"</h2><br><br>"; 
            }
            s=s+"<ul>";
            for(int l=0;l<cl.size();l++){
                s=s+"<li>"+cl.get(l).lib+" : "+cl.get(l).nom+" "+cl.get(l).nom_t+" :";
                if(cl.get(l).cour!=0) s=s+" "+cl.get(l).cour+" cours";
                if(cl.get(l).td!=0) s=s+" "+cl.get(l).td+" TD";
                if(cl.get(l).tp!=0) s=s+" "+cl.get(l).tp+" TP";
                s=s+"</li>";
            }
            s=s+"</ul></html>";            
            lbl=new JLabel(s, JLabel.CENTER);
            pan2=new JPanel();
            pan2.setBackground(Color.white);
            pan2.add(lbl);
            pan3.add(pan1);
            pan3.add(pan2);
            t.addTab(" "+pr.nom+" ", pan3);
            
        }
    }
    

    
}
