
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHADOW
 */
public class promo_fram extends javax.swing.JFrame {

    private promo pr=new promo();
    private module md=new module();
    private contien ct=new contien();
    private ArrayList<module> m ;
    private ArrayList<promo> p;
    private ArrayList<contien> c;
    private int code_p=0;
    /**
     * Creates new form module_fram
     */
    public promo_fram() {
        initComponents();
        load_promo();
        load_module("",0);
        load_promo_module();
        jMenuBar1.add(Box.createGlue());
        jMenuBar1.add(jMenu4);
        jMenuBar1.add(jMenu8);
        jMenuBar1.add(jMenu2);
        jMenu7.setSelected(true);
        if(ConBD.u.type==2){
            jMenu9.setVisible(false);
            jMenu1.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jsp = new javax.swing.JSpinner();
        pan = new javax.swing.JPanel();
        cmb = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        cour = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        td = new javax.swing.JSpinner();
        tp = new javax.swing.JSpinner();
        Recherch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sem = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("Affecter");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem3.setText("Supprimer");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem2.setText("Suprimer");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des promos");
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ajouter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre de groupe :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 30));

        nom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nom.setComponentPopupMenu(new pup());
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 260, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 80, 30));

        table2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Groupe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.setComponentPopupMenu(jPopupMenu1);
        table2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(table2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 310, 380));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nom :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 30));

        jsp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jsp.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        jPanel1.add(jsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 70, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 390, 530));

        pan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", " " }));
        pan.add(cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 400, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pan.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 80, 30));

        table1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Libelé", "Type", "Nom", "Semestre", "Cours", "TD", "TP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setComponentPopupMenu(jPopupMenu2);
        table1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table1);
        table1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setMaxWidth(100);
            table1.getColumnModel().getColumn(1).setMaxWidth(150);
            table1.getColumnModel().getColumn(2).setMaxWidth(450);
            table1.getColumnModel().getColumn(3).setMaxWidth(100);
            table1.getColumnModel().getColumn(4).setMaxWidth(50);
            table1.getColumnModel().getColumn(5).setMaxWidth(50);
            table1.getColumnModel().getColumn(6).setMaxWidth(50);
        }

        pan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 830, 380));

        cour.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pan.add(cour, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 69, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Recherch :");
        pan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Séance TD :");
        pan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, 30));

        td.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        td.setModel(new javax.swing.SpinnerNumberModel());
        pan.add(td, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 69, 30));

        tp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pan.add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 69, 30));

        Recherch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Recherch.setComponentPopupMenu(new pup());
        Recherch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RecherchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RecherchKeyTyped(evt);
            }
        });
        pan.add(Recherch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 330, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Séance cours :");
        pan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Séance TP :");
        pan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 90, 30));

        sem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semestre 1", "Semestre2" }));
        pan.add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 110, 30));

        jPanel2.add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 870, 530));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gérer les promos");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 350, 40));

        jMenu3.setText("Enseignant");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu5.setText("module");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu5MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("seance");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu6MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Promos");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu7MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu9.setText("EDT");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu9MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu1.setText("Utilisateur");
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Déconncter");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu8.setText("_");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu8MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Error-icon.png"))); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1350, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!nom.getText().equals("")) {
            promo p=new promo();
            JOptionPane.showMessageDialog(rootPane,p.add(nom.getText(), (int) jsp.getValue()));
            load_promo();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        try{
            code_p=p.get(table2.getSelectedRow()).code;
            pan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Affectation du "+table2.getValueAt(table2.getSelectedRow(), 0), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14)));
        }catch(Exception e) {
            System.err.print(e);
        }
        load_promo_module();
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        int code_m=0;
        try {
            code_m=c.get(table1.getSelectedRow()).code_m;
            int f=JOptionPane.showConfirmDialog(null,"Vouler vous suprimer ce module","Suprimer", JOptionPane.YES_NO_OPTION);
            if (f==0) {
                JOptionPane.showMessageDialog(null,ct.suprimer(code_p, code_m));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Selectioner un module");
        }
        load_promo_module();
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void RecherchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RecherchKeyReleased
        load_module(Recherch.getText(), -1);
    }//GEN-LAST:event_RecherchKeyReleased

    private void RecherchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RecherchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_RecherchKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int a=(int) cour.getValue();
        int b=(int) td.getValue();
        int c=(int) tp.getValue();
        int som=a+b+c;
        if(a>=0 && b>=0 && c>=0 && som!=0 && code_p!=0){
            int mr= m.get(cmb.getSelectedIndex()).code;
            JOptionPane.showMessageDialog(null,ct.add(mr, code_p, a, b, c,sem.getSelectedIndex()+1));
        }else JOptionPane.showMessageDialog(null,"Verifier les donnee");
        load_promo_module();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed
        module_fram mf=new module_fram();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu5MousePressed

    private void jMenu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MousePressed
        seance sf=new seance();
        sf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu6MousePressed

    private void jMenu7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MousePressed
        
    }//GEN-LAST:event_jMenu7MousePressed

    private void jMenu8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MousePressed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jMenu8MousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        System.exit(0);
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        Prof_fram pf=new Prof_fram();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu3MousePressed

    private void jMenu9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MousePressed
        Edt_fram em=new Edt_fram();
        em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu9MousePressed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        users_fram uf=new users_fram();
        uf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        int code=0;
        try {
            code=p.get(table2.getSelectedRow()).code;
            int f=JOptionPane.showConfirmDialog(null,"Vouler vous suprimer cette promo","Suprimer promo", JOptionPane.YES_NO_OPTION);
            if (f==0) {
                JOptionPane.showMessageDialog(null,pr.delet(code));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Selectioner une promo");
        }
        load_promo();
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
        ConBD.u=null;
        login l=new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(module_fram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(module_fram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(module_fram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(module_fram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new module_fram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Recherch;
    private javax.swing.JComboBox<String> cmb;
    private javax.swing.JSpinner cour;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jsp;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel pan;
    private javax.swing.JComboBox<String> sem;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JSpinner td;
    private javax.swing.JSpinner tp;
    // End of variables declaration//GEN-END:variables

    private void load_promo() {
        p=pr.getpromolist("");
        DefaultTableModel model = (DefaultTableModel)table2.getModel();
        model.setRowCount(0);
        Object[] row = new Object[2];
        for(int i = 0; i < p.size(); i++)
        {
            row[0] = p.get(i).nom;
            row[1] = p.get(i).nbr;
            model.addRow(row);
        }
    }

    private void load_module(String s,int r) {
        m = md.getmodulelist(s,r); 
        cmb.removeAllItems();
        for(int i = 0; i < m.size(); i++)
        {
            cmb.addItem(m.get(i).lib+" "+m.get(i).nom);
        }
    }

    private void load_promo_module() {
        c=ct.getmcontienlist(code_p, 0,0);
        DefaultTableModel model = (DefaultTableModel)table1.getModel();
        model.setRowCount(0);
        Object[] row = new Object[7];
        for(int i = 0; i < c.size(); i++)
        {
            row[0] = c.get(i).lib;
            row[1] = c.get(i).nom_t;
            row[2] = c.get(i).nom;
            row[3] = c.get(i).nom_s;
            row[4] = c.get(i).cour;
            row[5] = c.get(i).td;
            row[6] = c.get(i).tp;
            model.addRow(row);
        }
    }
}
